services:
  nanoframework-build:
    image: diseqc/nanoframework-build:local
    build:
      context: .
      dockerfile: Dockerfile.build
    container_name: diseqc-build
    volumes:
      # Mount your project directory
      - .:/work
      # Mount nf-interpreter (will be cloned if not exists)
      - nf-interpreter:/nf-interpreter
    working_dir: /work

volumes:
  nf-interpreter:
    driver: local
